language: java

matrix:
  include:
    - jdk: openjdk7
    - jdk: oraclejdk7
      dist: precise
    - jdk: oraclejdk8
    - jdk: oraclejdk9

install: mvn install -Dgpg.skip=true -DskipTests

notifications:
  email:
    on_success: never

sudo: false
